# Generated by Django 4.2.3 on 2023-07-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
