# Generated by Django 4.2.3 on 2023-07-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='pos',
            new_name='post',
        ),
    ]
